FROM python:3.9-slim-bullseye

RUN apt-get update && \
    apt-get install -y openssh-client openssh-server curl --no-install-recommends && \
    mkdir /etc/apt/keyrings && \
    curl -fsSL https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public | sudo tee /etc/apt/keyrings/salt-archive-keyring.pgp && \
    curl -fsSL https://github.com/saltstack/salt-install-guide/releases/latest/download/salt.sources | sudo tee /etc/apt/sources.list.d/salt.sources && \
    apt-get update && \
    apt-get install -y salt-minion && \
    apt-get clean 
    
COPY salt_nornir/ /tmp/salt_nornir/
COPY nornir_salt/ /tmp/nornir_salt/

RUN salt-pip install --no-cache-dir /tmp/nornir_salt/.[prodmaxminion] --upgrade && \
    salt-pip install --no-cache-dir /tmp/salt_nornir/.[prodmaxminion] --upgrade

ENTRYPOINT salt-proxy --proxyid=$PROXY_ID -l trace