FROM python:3.9-slim-bullseye

COPY salt_nornir/test/master_start.sh /tmp/master_start.sh

RUN apt-get update && \
    apt-get install -y curl --no-install-recommends   && \
    mkdir /etc/apt/keyrings  && \
    curl -fsSL https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public | sudo tee /etc/apt/keyrings/salt-archive-keyring.pgp && \
    curl -fsSL https://github.com/saltstack/salt-install-guide/releases/latest/download/salt.sources | sudo tee /etc/apt/sources.list.d/salt.sources && \
    apt-get update  && \
    apt-get install -y salt-master salt-api  && \
    apt-get clean  && \
    useradd -m saltuser  && \
    usermod -g root saltuser  && \
    chmod 775 /tmp/master_start.sh  && \
    python -m pip install --no-cache-dir pip setuptools wheel poetry rich pynetbox salt --upgrade

COPY salt_nornir/ /tmp/salt_nornir/
COPY nornir_salt/ /tmp/nornir_salt/

RUN salt-pip install --no-cache-dir /tmp/nornir_salt/.[prodmaxmaster] --upgrade && \
    salt-pip install --no-cache-dir /tmp/salt_nornir/.[prodmaxmaster] --upgrade

# CMD /tmp/master_start.sh
ENTRYPOINT salt-master -l trace