services: 
  salt-master:
    container_name: salt-master
    hostname: 'salt-master'
    build:
      context: .
      dockerfile: test/Dockerfile.master
    networks: 
      net0:
        ipv4_address: 10.0.0.2
    volumes:
      # bind folder with tests to salt-master container
      - type: bind
        source: ./test/pytest/
        target: /tmp/pytest/
      # bind folder with salt-master configuration to salt-master container
      - type: bind
        source: ./test/salt_master_files/
        target: /etc/salt/
        
  salt-minion:
    container_name: salt-minion
    hostname: 'salt-minion'
    build:
      context: .
      dockerfile: test/Dockerfile.minion
    networks: 
      net0:
        ipv4_address: 10.0.0.3
      net1:
        ipv4_address: 10.0.1.3
    depends_on:
      - salt-master
    volumes:
      # bind Salt Nornir packages for the ease of development/debugging
      - type: bind
        source: ./salt_nornir/
        target: /usr/local/lib/python3.6/site-packages/salt_nornir/
      - type: bind
        source: ./nornir_salt/nornir_salt/
        target: /usr/local/lib/python3.6/site-packages/nornir_salt/

  ceos1:
    container_name: ceos1
    hostname: 'ceos1'
    privileged: true
    build:
      context: .
      dockerfile: test/Dockerfile.ceos1
    networks:
      # need ceos-dummy as its assigned to linux OS so that 
      # second network assigned to cEOS instance
      ceos-dummy: {}
      net1:
        ipv4_address: 10.0.1.4

  ceos2:
    container_name: ceos2
    hostname: 'ceos2'
    privileged: true
    build:
      context: .
      dockerfile: test/Dockerfile.ceos2
    networks:
      ceos-dummy: {}
      net1:
        ipv4_address: 10.0.1.5
      
networks:
  net0:
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
  net1:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  ceos-dummy: {}
