services:
  salt-master:
    container_name: salt-master
    hostname: 'salt-master'
    privileged: True
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add: 
      - SYS_PTRACE
    build:
      context: ..
      dockerfile: salt_nornir/test/Dockerfile.py39.master
    networks:
      net0:
        ipv4_address: 10.0.0.2
    volumes:
      # bind folder with tests to salt-master container
      - type: bind
        source: ./test/pytest/
        target: /tmp/pytest/
      # bind folder with salt-master configuration to salt-master container
      - type: bind
        source: ./test/salt_master_files/
        target: /etc/salt/
      # bind Salt Nornir packages for the ease of development/debugging
      - type: bind
        source: ./salt_nornir/
        target: /usr/local/lib/python3.9/site-packages/salt_nornir/
      - type: bind
        source: ../nornir_salt/nornir_salt/
        target: /usr/local/lib/python3.9/site-packages/nornir_salt/
      # bind local folder to salt-master in case need to pip install nornir-salt
      - type: bind
        source: ../nornir_salt/
        target: /tmp/nornir_salt/
      - type: bind
        source: .
        target: /tmp/salt_nornir/
      # bind PICLE package for development
      - type: bind
        source: ../PICLE/picle
        target: /usr/local/lib/python3.9/site-packages/picle/

  salt-minion-nrp1:
    container_name: salt-minion-nrp1
    hostname: 'salt-minion-nrp1'
    privileged: True
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add: 
      - SYS_PTRACE
    build:
      context: ..
      dockerfile: salt_nornir/test/Dockerfile.py39.minion
    environment:
      PROXY_ID: "nrp1"
    networks:
      net0:
        ipv4_address: 10.0.0.3
      net1:
        ipv4_address: 10.0.1.3
    depends_on:
      - salt-master
    volumes:
      # bind Salt Nornir packages for the ease of development/debugging
      - type: bind
        source: ./salt_nornir/
        target: /usr/local/lib/python3.9/site-packages/salt_nornir/
      - type: bind
        source: ../nornir_salt/nornir_salt/
        target: /usr/local/lib/python3.9/site-packages/nornir_salt/
      # bind local folder to salt-minion in case need to pip install nornir-salt
      - type: bind
        source: ../nornir_salt/
        target: /tmp/nornir_salt/
      - type: bind
        source: .
        target: /tmp/salt_nornir/
      # bind TTP Templates package for development
      - type: bind
        source: ../TTP_templates/ttp_templates
        target: /usr/local/lib/python3.9/site-packages/ttp_templates/

  salt-minion-nrp2:
    container_name: salt-minion-nrp2
    hostname: 'salt-minion-nrp2'
    # privileged: True
    # security_opt:
    #   - seccomp:unconfined
    #   - apparmor:unconfined
    # cap_add: 
    #   - SYS_PTRACE
    build:
      context: ..
      dockerfile: salt_nornir/test/Dockerfile.py39.minion
    environment:
      PROXY_ID: "nrp2"
    networks:
      net0:
        ipv4_address: 10.0.0.6
      net1:
        ipv4_address: 10.0.1.6
    depends_on:
      - salt-master
    volumes:
      # bind Salt Nornir packages for the ease of development/debugging
      - type: bind
        source: ./salt_nornir/
        target: /usr/local/lib/python3.9/site-packages/salt_nornir/
      - type: bind
        source: ../nornir_salt/nornir_salt/
        target: /usr/local/lib/python3.9/site-packages/nornir_salt/
      # bind local folder to salt-minion in case need to pip install nornir-salt
      - type: bind
        source: ../nornir_salt/
        target: /tmp/nornir_salt/
      - type: bind
        source: .
        target: /tmp/salt_nornir/
      # bind TTP Templates package for development
      - type: bind
        source: ../TTP_templates/ttp_templates
        target: /usr/local/lib/python3.9/site-packages/ttp_templates/

  salt-minion-nrp3:
    container_name: salt-minion-nrp3
    hostname: 'salt-minion-nrp3'
    # privileged: True
    # security_opt:
    #   - seccomp:unconfined
    #   - apparmor:unconfined
    # cap_add: 
    #   - SYS_PTRACE
    build:
      context: ..
      dockerfile: salt_nornir/test/Dockerfile.py39.minion
    environment:
      PROXY_ID: "nrp3"
    networks:
      net0:
        ipv4_address: 10.0.0.7
      net1:
        ipv4_address: 10.0.1.7
    depends_on:
      - salt-master
    volumes:
      # bind Salt Nornir packages for the ease of development/debugging
      - type: bind
        source: ./salt_nornir/
        target: /usr/local/lib/python3.9/site-packages/salt_nornir/
      - type: bind
        source: ../nornir_salt/nornir_salt/
        target: /usr/local/lib/python3.9/site-packages/nornir_salt/
      # bind local folder to salt-minion in case need to pip install nornir-salt
      - type: bind
        source: ../nornir_salt/
        target: /tmp/nornir_salt/
      - type: bind
        source: .
        target: /tmp/salt_nornir/
      # bind TTP Templates package for development
      - type: bind
        source: ../TTP_templates/ttp_templates
        target: /usr/local/lib/python3.9/site-packages/ttp_templates/

  ceos1:
    container_name: ceos1
    hostname: 'ceos1'
    privileged: true
    build:
      context: ..
      dockerfile: salt_nornir/test/Dockerfile.ceos1
    networks:
      # need ceos-dummy as its assigned to linux OS so that
      # second network assigned to cEOS instance
      ceos-dummy: {}
      net1:
        ipv4_address: 10.0.1.4

  ceos2:
    container_name: ceos2
    hostname: 'ceos2'
    privileged: true
    build:
      context: ..
      dockerfile: salt_nornir/test/Dockerfile.ceos2
    networks:
      ceos-dummy: {}
      net1:
        ipv4_address: 10.0.1.5

  salt-nornir-fakenos:
    container_name: salt-nornir-fakenos
    hostname: 'salt-nornir-fakenos'
    privileged: true
    build:
      context: ..
      dockerfile: salt_nornir/test/Dockerfile.py39.fakenos
    volumes:
      # bind fakenos inventory
      - type: bind
        source: ./test/fakenos_inventory/
        target: /tmp/fakenos_inventory/
      # bind FakeNOS packages for the ease of development/debugging
      - type: bind
        source: ../fakenos/fakenos/
        target: /usr/local/lib/python3.9/site-packages/fakenos/
    networks:
      ceos-dummy: {}
      net1:
        ipv4_address: 10.0.1.10
networks:
  net0:
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
  net1:
    ipam:
      config:
        - subnet: 10.0.1.0/24
  ceos-dummy: {}
